// Package fixtures reads spec/conformance/fixtures.json and turns it into
// the records a server under test must hold before any case runs. The Go
// conformance runner and cmd/tunna-fixtures both provision from here, so a
// runner in another language replays the same cases against the same state
// (ADR-0010). Like every internal package it imports only the root and sig;
// the caller chooses the stores.
package fixtures

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"hash/crc32"
	"os"
	"time"

	"github.com/tunnaio/tunna"
	"github.com/tunnaio/tunna/sig"
)

// File is fixtures.json, the subset of its schema a runner needs.
type File struct {
	Spec   string `json:"spec"`
	Server struct {
		CORSOrigins []string `json:"cors_origins"`
	} `json:"server"`
	Keys    map[string]Key    `json:"keys"`
	Buckets map[string]Bucket `json:"buckets"`
}

// Key is one API key fixture. Secrets here are test-only by construction.
type Key struct {
	ID       string            `json:"id"`
	Secret   string            `json:"secret"`
	Name     string            `json:"name"`
	Admin    bool              `json:"admin"`
	Scopes   map[string]string `json:"scopes"`
	Disabled bool              `json:"disabled"`
}

// Bucket is one bucket fixture. The map key in File.Buckets is the bucket
// name unless Name overrides it.
type Bucket struct {
	Name    string   `json:"name"`
	Public  bool     `json:"public"`
	Objects []Object `json:"objects"`
}

// Object is a pre-existing object: literal text or generated bytes.
type Object struct {
	Key         string  `json:"key"`
	ContentType string  `json:"content_type"`
	Text        *string `json:"text"`
	Bytes       *Bytes  `json:"bytes"`
}

// Bytes names a deterministic byte stream: see Generate.
type Bytes struct {
	Seed   int64 `json:"seed"`
	Length int64 `json:"length"`
}

// Load reads and parses a fixtures file.
func Load(path string) (File, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return File{}, err
	}
	var f File
	if err := json.Unmarshal(raw, &f); err != nil {
		return File{}, fmt.Errorf("%s: %w", path, err)
	}
	return f, nil
}

// Generate is the sha256-counter byte generator fixtures.json describes:
// byte i of the stream for seed s is byte (i mod 32) of SHA-256 over the
// 16-byte big-endian concatenation of s and floor(i / 32). Every runner in
// every language implements this same function.
func Generate(seed, length int64) []byte {
	out := make([]byte, 0, length)
	var block [16]byte
	binary.BigEndian.PutUint64(block[:8], uint64(seed))
	for counter := int64(0); int64(len(out)) < length; counter++ {
		binary.BigEndian.PutUint64(block[8:], uint64(counter))
		sum := sha256.Sum256(block[:])
		out = append(out, sum[:]...)
	}
	return out[:length]
}

// Has reports whether name is a key or bucket fixture, which is what a
// case's "fixtures" list may name.
func (f File) Has(name string) bool {
	_, isKey := f.Keys[name]
	_, isBucket := f.Buckets[name]
	return isKey || isBucket
}

// SigKey returns the signing key for a key fixture, for building requests.
func (f File) SigKey(name string) (sig.Key, bool) {
	k, ok := f.Keys[name]
	if !ok {
		return sig.Key{}, false
	}
	return sig.Key{ID: k.ID, Secret: k.Secret}, true
}

// Origins parses the server section's allowlist.
func (f File) Origins() (tunna.Origins, error) {
	return tunna.ParseOrigins(f.Server.CORSOrigins)
}

// APIKeys returns every key fixture as the server should hold it, disabled
// ones included, all created at the given time.
func (f File) APIKeys(createdAt time.Time) []tunna.APIKey {
	out := make([]tunna.APIKey, 0, len(f.Keys))
	for _, k := range f.Keys {
		key := tunna.APIKey{ID: k.ID, Secret: k.Secret, Name: k.Name, Admin: k.Admin, Disabled: k.Disabled, CreatedAt: createdAt}
		if len(k.Scopes) > 0 {
			key.Scopes = make(map[string]tunna.Access, len(k.Scopes))
			for bucket, level := range k.Scopes {
				key.Scopes[bucket] = tunna.Access(level)
			}
		}
		out = append(out, key)
	}
	return out
}

// BucketRecords returns every bucket fixture as the server should hold it.
func (f File) BucketRecords(createdAt time.Time) []tunna.Bucket {
	out := make([]tunna.Bucket, 0, len(f.Buckets))
	for key, b := range f.Buckets {
		out = append(out, tunna.Bucket{Name: bucketName(key, b), Public: b.Public, CreatedAt: createdAt})
	}
	return out
}

// ObjectRecords writes every fixture object's bytes into blobs and returns
// the metadata rows pointing at them, checksummed the way the server would
// (ADR-0006), so a case can expect the same ETag a real PUT produces.
func (f File) ObjectRecords(ctx context.Context, blobs tunna.BlobStore, createdAt time.Time) ([]tunna.Object, error) {
	table := crc32.MakeTable(crc32.Castagnoli)
	var out []tunna.Object
	for key, b := range f.Buckets {
		bucket := bucketName(key, b)
		for _, o := range b.Objects {
			var data []byte
			switch {
			case o.Text != nil:
				data = []byte(*o.Text)
			case o.Bytes != nil:
				data = Generate(o.Bytes.Seed, o.Bytes.Length)
			}
			id, err := blobs.Create(ctx)
			if err != nil {
				return nil, fmt.Errorf("fixture %s/%s: create blob: %w", bucket, o.Key, err)
			}
			if _, err := blobs.Write(ctx, id, 0, bytes.NewReader(data)); err != nil {
				return nil, fmt.Errorf("fixture %s/%s: write blob: %w", bucket, o.Key, err)
			}
			ct := o.ContentType
			if ct == "" {
				ct = "application/octet-stream"
			}
			out = append(out, tunna.Object{
				Bucket: bucket, Key: o.Key, BlobID: id,
				Size: int64(len(data)), ContentType: ct,
				Checksum:  sig.EncodeCRC32C(crc32.Checksum(data, table)),
				CreatedAt: createdAt,
			})
		}
	}
	return out, nil
}

func bucketName(key string, b Bucket) string {
	if b.Name != "" {
		return b.Name
	}
	return key
}
