// Shared access to the spec files. Tests read them by relative path; the
// package does not ship them.

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

const specDir = new URL("../../../spec/", import.meta.url);

export function loadSpec<T>(relative: string): T {
  return JSON.parse(readFileSync(new URL(relative, specDir), "utf8")) as T;
}

export function specVersion(): string {
  return readFileSync(new URL("VERSION", specDir), "utf8").trim();
}

/** A vector input: literal text, hex, or a generated byte stream. */
export type Input = { text?: string; hex?: string; bytes?: { seed: number; length: number } };

/**
 * The sha256-counter generator every runner implements (fixtures.json): byte
 * i of the stream for seed s is byte (i mod 32) of SHA-256 over the 16-byte
 * big-endian concatenation of s and floor(i / 32).
 */
export function generate(seed: number, length: number): Uint8Array {
  const out = new Uint8Array(length);
  const block = new Uint8Array(16);
  const view = new DataView(block.buffer);
  view.setBigUint64(0, BigInt(seed));
  for (let offset = 0, counter = 0; offset < length; offset += 32, counter++) {
    view.setBigUint64(8, BigInt(counter));
    const sum = createHash("sha256").update(block).digest();
    out.set(sum.subarray(0, Math.min(32, length - offset)), offset);
  }
  return out;
}

/** Bytes for a vector input. */
export function inputBytes(input: Input): Uint8Array {
  if (input.text !== undefined) return new TextEncoder().encode(input.text);
  if (input.hex !== undefined) return Uint8Array.from(Buffer.from(input.hex, "hex"));
  if (input.bytes !== undefined) return generate(input.bytes.seed, input.bytes.length);
  throw new Error("vector input has no text, hex or bytes");
}
